
#Linux-Image als Basis
FROM ubuntu:latest

# enviroment variable "Hello world" festlegen
ENV GREETING="Hello world"

#CMD-Befehlnutzen, um die Konsolenausgabe zu erstellen
CMD ["/bin/sh", "-c", "echo $GREETING"]

